# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: publish
      run: dotnet publish -c Release -o myapp
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: myapp
  
  deployTesting:
    needs: build
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - name: Download artifact for deployment job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: myapp
    - name: Deploy to testing
      run: echo "Deploying to testing environment"

  deployProduction:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download artifact for deployment job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: myapp
    - name: Deploy to production
      run: echo "Deploying to production environment"